
.PHONY: docker-presto
docker-presto: docker-exist
	@${DOCKER_CMD} stop d18n-presto 2>/dev/null || true
	@${DOCKER_CMD} wait d18n-presto 2>/dev/null >/dev/null || true
	@${DOCKER_CMD} rm d18n-presto 2>/dev/null >/dev/null || true
	@${DOCKER_CMD} run -d ${DOCKER_RM} \
	-p 8080:8080 \
	--name d18n-presto \
	starburstdata/presto

.PHONY: test-presto-cli
test-presto-cli:
	@./bin/d18n --host 127.0.0.1 --port 8080 -server presto \
	--user username \
	-verbose \
	-query "select 1, 'abc', '中文'"
