# Useful SQLs
## Version of sqlite
# select sqlite_version()
## show tables
# SELECT '' AS table_schema, name AS table_name FROM sqlite_master WHERE type = 'table' AND name != 'sqlite_sequence' ORDER BY name

.PHONY: test-sqlite
test-sqlite: build
	# test sqlite query
	@./bin/d18n --server sqlite \
	--database 'test/sakila.sqlite3' \
	--query 'select * from actor' \
	--limit 2
	# test detect text for nil ScanType
	@./bin/d18n \
	--detect --server sqlite \
	--table film_text \
	--database test/sakila.sqlite3
	# test BLOB
	@./bin/d18n --server sqlite \
	--database 'test/sakila.sqlite3' \
	--query "SELECT X'31' as c1, typeof(x'31'), 1 as c2, typeof(1), '1' as c3, typeof('1')"
	@./bin/d18n --server sqlite \
	--database 'test/sakila.sqlite3' \
	--hex-blob c1,c2 \
	--file test/test_sqlite_blob.sql \
	--query "SELECT X'31' as c1, '1', 1, x'61' as c2, 'a'"
